name: AntiSpoof
version: ${project.version}
main: com.gigazelensky.antispoof.AntiSpoofPlugin
softdepend: [ProtocolLib, ProtocolSupport, ViaVersion, ViaBackwards, ViaRewind, Geyser-Spigot, PlaceholderAPI, GrimAC, floodgate]
# Add PacketEvents as an optional dependency for the lite version
loadbefore: [PacketEvents]
commands:
  antispoof:
    description: View client channel information and manage the plugin
    usage: /antispoof help
    permission: antispoof.command
permissions:
  antispoof.command:
    description: Access to AntiSpoof commands
    default: op
  antispoof.admin:
    description: Access to admin commands like reload
    default: op
  antispoof.alerts:
    description: Receive spoof alerts
    default: op
  antispoof.bypass:
    description: Bypass all spoof checks
    default: false
